import "./globals.css";
import { Inter } from "next/font/google";
import { getUser } from "@/lib/auth.service";
import { Header } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " flex h-dynamic flex-col bg-zinc-900 text-slate-200"
        }
      >
        <Header user={user} />
        <main className="container mx-auto flex flex-1 flex-col gap-4 p-4 lg:px-0">
          {children}
        </main>
      </body>
    </html>
  );
}
